import Link from "next/link";
import { Package, Settings, TrendingUp, Plus, ArrowRight, ShieldCheck } from "lucide-react";
import { sampleProducts } from "@/lib/demo-data";
import { getCurrentGoldRate } from "@/lib/rates";

export default async function AdminDashboard() {
  const rate = await getCurrentGoldRate();
  const available = sampleProducts.filter(p=>p.availability==="AVAILABLE").length;
  const sold = sampleProducts.filter(p=>p.availability==="SOLD").length;
  return <main className="min-h-screen bg-[#f1ece2]"><AdminNav/><section className="mx-auto max-w-6xl px-4 py-7 sm:px-8"><p className="text-xs text-ink/50">Admin dashboard</p><h1 className="serif mt-1 text-5xl">Good morning 👋</h1><div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat title="22K Gold Rate" value={`₹${rate.toLocaleString("en-IN")}/g`} icon={<TrendingUp/>}/><Stat title="Products" value={sampleProducts.length.toString()} icon={<Package/>}/><Stat title="Available" value={available.toString()} icon={<ShieldCheck/>}/></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Link href="/admin/products/new" className="rounded-2xl bg-ink p-6 text-ivory"><Plus className="text-gold"/><h2 className="serif mt-8 text-3xl">Add Product</h2><p className="mt-2 text-xs text-ivory/55">Create a catalogue item and upload photos.</p></Link><Link href="/admin/products" className="rounded-2xl bg-white p-6"><Package className="text-gold"/><h2 className="serif mt-8 text-3xl">Inventory</h2><p className="mt-2 text-xs text-ink/55">Manage availability, sold items and product details.</p></Link><Link href="/admin/rates" className="rounded-2xl bg-white p-6"><TrendingUp className="text-gold"/><h2 className="serif mt-8 text-3xl">Rate History</h2><p className="mt-2 text-xs text-ink/55">Review accepted market reference rates.</p></Link><Link href="/admin/settings" className="rounded-2xl bg-white p-6"><Settings className="text-gold"/><h2 className="serif mt-8 text-3xl">Pricing Settings</h2><p className="mt-2 text-xs text-ink/55">Manage making charge and GST rules.</p></Link></div></section></main>;
}
function Stat({title,value,icon}:{title:string,value:string,icon:React.ReactNode}){return <div className="rounded-2xl bg-white p-5"><div className="flex justify-between text-gold">{icon}</div><p className="mt-8 text-[10px] uppercase tracking-[.16em] text-ink/45">{title}</p><p className="serif mt-1 text-4xl">{value}</p></div>}
function AdminNav(){return <header className="border-b border-ink/10 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5 sm:px-8"><Link href="/admin" className="serif text-xl tracking-[.15em]">RANIMA <span className="ml-2 text-[8px] font-sans tracking-[.3em] text-gold">ADMIN</span></Link><Link href="/" className="text-[10px] uppercase tracking-[.15em] text-ink/50">View site</Link></div></header>}